package java.sql;

import java.NativeArray;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLWarning;
import java.sql.Wrapper;

/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html */
@:native("java.sql.Statement")
extern interface Statement implements Wrapper
{
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#addBatch(java.lang.String) */
	public function addBatch(sql:String):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#cancel() */
	public function cancel():Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#clearBatch() */
	public function clearBatch():Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#clearWarnings() */
	public function clearWarnings():Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#close() */
	public function close():Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#execute(java.lang.String, int) */
	@:overload(function (sql:String, autoGeneratedKeys:Int):Bool {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#execute(java.lang.String, int[]) */
	@:overload(function (sql:String, columnIndexes:NativeArray<Int>):Bool {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#execute(java.lang.String, java.lang.String[]) */
	@:overload(function (sql:String, columnNames:NativeArray<String>):Bool {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#execute(java.lang.String) */
	public function execute(sql:String):Bool;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#executeBatch() */
	public function executeBatch():NativeArray<Int>;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#executeQuery(java.lang.String) */
	public function executeQuery(sql:String):ResultSet;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#executeUpdate(java.lang.String, int) */
	@:overload(function (sql:String, autoGeneratedKeys:Int):Int {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#executeUpdate(java.lang.String, int[]) */
	@:overload(function (sql:String, columnIndexes:NativeArray<Int>):Int {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#executeUpdate(java.lang.String, java.lang.String[]) */
	@:overload(function (sql:String, columnNames:NativeArray<String>):Int {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#executeUpdate(java.lang.String) */
	public function executeUpdate(sql:String):Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getConnection() */
	public function getConnection():Connection;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getFetchDirection() */
	public function getFetchDirection():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getFetchSize() */
	public function getFetchSize():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getGeneratedKeys() */
	public function getGeneratedKeys():ResultSet;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getMaxFieldSize() */
	public function getMaxFieldSize():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getMaxRows() */
	public function getMaxRows():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getMoreResults(int) */
	@:overload(function (current:Int):Bool {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getMoreResults() */
	public function getMoreResults():Bool;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getQueryTimeout() */
	public function getQueryTimeout():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getResultSet() */
	public function getResultSet():ResultSet;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getResultSetConcurrency() */
	public function getResultSetConcurrency():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getResultSetHoldability() */
	public function getResultSetHoldability():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getResultSetType() */
	public function getResultSetType():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getUpdateCount() */
	public function getUpdateCount():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getWarnings() */
	public function getWarnings():SQLWarning;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#isClosed() */
	public function isClosed():Bool;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#isPoolable() */
	public function isPoolable():Bool;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setCursorName(java.lang.String) */
	public function setCursorName(name:String):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setEscapeProcessing(boolean) */
	public function setEscapeProcessing(enable:Bool):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setFetchDirection(int) */
	public function setFetchDirection(direction:Int):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setFetchSize(int) */
	public function setFetchSize(rows:Int):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setMaxFieldSize(int) */
	public function setMaxFieldSize(max:Int):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setMaxRows(int) */
	public function setMaxRows(max:Int):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setPoolable(boolean) */
	public function setPoolable(poolable:Bool):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setQueryTimeout(int) */
	public function setQueryTimeout(seconds:Int):Void;

}

