package java.sql;

import java.NativeArray;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLWarning;
import java.sql.Wrapper;

/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html */
@:native("java.sql.Statement")
extern interface Statement implements Wrapper
{
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#addBatch(java.lang.String) */
	/*@@@ modifiers=1025 */ public function addBatch(sql:String):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#cancel() */
	/*@@@ modifiers=1025 */ public function cancel():Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#clearBatch() */
	/*@@@ modifiers=1025 */ public function clearBatch():Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#clearWarnings() */
	/*@@@ modifiers=1025 */ public function clearWarnings():Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#close() */
	/*@@@ modifiers=1025 */ public function close():Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#execute(java.lang.String, int) */
	/*@@@ modifiers=1025 */ @:overload(function (sql:String, autoGeneratedKeys:Int):Bool {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#execute(java.lang.String, int[]) */
	/*@@@ modifiers=1025 */ @:overload(function (sql:String, columnIndexes:NativeArray<Int>):Bool {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#execute(java.lang.String, java.lang.String[]) */
	/*@@@ modifiers=1025 */ @:overload(function (sql:String, columnNames:NativeArray<String>):Bool {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#execute(java.lang.String) */
	/*@@@ modifiers=1025 */ public function execute(sql:String):Bool;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#executeBatch() */
	/*@@@ modifiers=1025 */ public function executeBatch():NativeArray<Int>;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#executeQuery(java.lang.String) */
	/*@@@ modifiers=1025 */ public function executeQuery(sql:String):ResultSet;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#executeUpdate(java.lang.String, int) */
	/*@@@ modifiers=1025 */ @:overload(function (sql:String, autoGeneratedKeys:Int):Int {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#executeUpdate(java.lang.String, int[]) */
	/*@@@ modifiers=1025 */ @:overload(function (sql:String, columnIndexes:NativeArray<Int>):Int {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#executeUpdate(java.lang.String, java.lang.String[]) */
	/*@@@ modifiers=1025 */ @:overload(function (sql:String, columnNames:NativeArray<String>):Int {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#executeUpdate(java.lang.String) */
	/*@@@ modifiers=1025 */ public function executeUpdate(sql:String):Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getConnection() */
	/*@@@ modifiers=1025 */ public function getConnection():Connection;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getFetchDirection() */
	/*@@@ modifiers=1025 */ public function getFetchDirection():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getFetchSize() */
	/*@@@ modifiers=1025 */ public function getFetchSize():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getGeneratedKeys() */
	/*@@@ modifiers=1025 */ public function getGeneratedKeys():ResultSet;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getMaxFieldSize() */
	/*@@@ modifiers=1025 */ public function getMaxFieldSize():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getMaxRows() */
	/*@@@ modifiers=1025 */ public function getMaxRows():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getMoreResults(int) */
	/*@@@ modifiers=1025 */ @:overload(function (current:Int):Bool {})
	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getMoreResults() */
	/*@@@ modifiers=1025 */ public function getMoreResults():Bool;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getQueryTimeout() */
	/*@@@ modifiers=1025 */ public function getQueryTimeout():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getResultSet() */
	/*@@@ modifiers=1025 */ public function getResultSet():ResultSet;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getResultSetConcurrency() */
	/*@@@ modifiers=1025 */ public function getResultSetConcurrency():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getResultSetHoldability() */
	/*@@@ modifiers=1025 */ public function getResultSetHoldability():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getResultSetType() */
	/*@@@ modifiers=1025 */ public function getResultSetType():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getUpdateCount() */
	/*@@@ modifiers=1025 */ public function getUpdateCount():Int;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#getWarnings() */
	/*@@@ modifiers=1025 */ public function getWarnings():SQLWarning;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#isClosed() */
	/*@@@ modifiers=1025 */ public function isClosed():Bool;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#isPoolable() */
	/*@@@ modifiers=1025 */ public function isPoolable():Bool;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setCursorName(java.lang.String) */
	/*@@@ modifiers=1025 */ public function setCursorName(name:String):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setEscapeProcessing(boolean) */
	/*@@@ modifiers=1025 */ public function setEscapeProcessing(enable:Bool):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setFetchDirection(int) */
	/*@@@ modifiers=1025 */ public function setFetchDirection(direction:Int):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setFetchSize(int) */
	/*@@@ modifiers=1025 */ public function setFetchSize(rows:Int):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setMaxFieldSize(int) */
	/*@@@ modifiers=1025 */ public function setMaxFieldSize(max:Int):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setMaxRows(int) */
	/*@@@ modifiers=1025 */ public function setMaxRows(max:Int):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setPoolable(boolean) */
	/*@@@ modifiers=1025 */ public function setPoolable(poolable:Bool):Void;

	/** @REF http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#setQueryTimeout(int) */
	/*@@@ modifiers=1025 */ public function setQueryTimeout(seconds:Int):Void;

}

